version: '2'
services:
  db:
    image: 'wordpress-demo-education-db:latest'
    restart: 'always'
  wordpress:
    image: 'wordpress-demo-education-wordpress:latest'
    restart: 'always'
    environment: 
      - WORDPRESS_DB_HOST=db
    ports: 
      - '80:80'

